apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    name: flask-service
    app: flask-app
spec:
  type: NodePort
  ports:
  - port: 80          # External port to expose the service
    targetPort: 8000  # Port the Pod listens on
    nodePort: 30004   # NodePort for external access
  selector:
    app: flask-app    # Matches the "app" label in the Pod

