apiVersion: v1
kind: Pod
metadata:
 name: flask-app-pod
 labels:
   name: flask-app-pod
   app: flask-app
spec:
 containers:
  - name: flask-app-pod
    image: taha2606/test-repo:latest
    ports:
    - containerPort: 8000
